### PR TITLE
Add server-side library development section, link to log levels; improve wording

### PR DESCRIPTION
**Pull request by ktoso**

### CODE REVIEW

**Comment by ktoso** [comment]
resolves https://github.com/swift-server/guides/issues/38

**Review by tomerd — COMMENTED** [review]
does this really rise to a top level item? maybe we need an "architecture" or "design" top level that has links to guides like lifecycle, logging, metrics, tracing, etc

**Comment by kmahar** [comment]
I like the suggestion to sort the items in the list into categories a little more, especially given that we want to keep building out guides further. 
we could probably group all the debugging related links under one "debugging" top level bullet?

**Comment by ktoso** [comment]
Sounds good, lemme try to do that here

**Comment by ktoso** [comment]
What about this @kmahar @tomerd ?

I also applied some of nice @wsargent's comments from the other thread

**Review by kmahar — APPROVED** [review]
lgtm

**Review by tomerd — APPROVED** [review]

**Comment by ktoso** [comment]
Thanks!

**Pull request merged**
